/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.system.student;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ManageStudentsInfo extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudentsInfo
     */
    student std = new student();
    DefaultTableModel model;
    public ManageStudentsInfo() {
        initComponents();
        std.fillStudentJtable(jTable1,"");
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton_fema);
        bg.add(jRadioButton_male);
        model =(DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.black);
        jTable1.setSelectionBackground(Color.black);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_tp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_add = new javax.swing.JTextArea();
        jDateChooserBirth = new com.toedter.calendar.JDateChooser();
        jRadioButton_fema = new javax.swing.JRadioButton();
        jRadioButton_male = new javax.swing.JRadioButton();
        jTextField_LName = new javax.swing.JTextField();
        jTextField_FName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_mange_add = new javax.swing.JButton();
        jButton_manage_remove = new javax.swing.JButton();
        jButton_mange_clear = new javax.swing.JButton();
        jLabel_id = new javax.swing.JLabel();
        jTextField_stid = new javax.swing.JTextField();
        jButton_edit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_searchStu = new javax.swing.JTextField();
        jLabel_slbl = new javax.swing.JLabel();
        jButton_studentCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TP_NO :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Birth of date :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Gender :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Last Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name :");

        jTextField_tp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tpActionPerformed(evt);
            }
        });
        jTextField_tp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_tpKeyTyped(evt);
            }
        });

        jTextArea_add.setColumns(20);
        jTextArea_add.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea_add.setRows(5);
        jScrollPane1.setViewportView(jTextArea_add);

        jDateChooserBirth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jRadioButton_fema.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton_fema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton_fema.setText("Female");

        jRadioButton_male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton_male.setText("Male");

        jTextField_LName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LNameActionPerformed(evt);
            }
        });

        jTextField_FName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Manage Students Info");

        jButton_mange_add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_mange_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add stu.png"))); // NOI18N
        jButton_mange_add.setText("Add");
        jButton_mange_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mange_addActionPerformed(evt);
            }
        });

        jButton_manage_remove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_manage_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png"))); // NOI18N
        jButton_manage_remove.setText("Remove");
        jButton_manage_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_manage_removeActionPerformed(evt);
            }
        });

        jButton_mange_clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_mange_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Clear-icon.png"))); // NOI18N
        jButton_mange_clear.setText("Clear");
        jButton_mange_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mange_clearActionPerformed(evt);
            }
        });

        jLabel_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_id.setText("Student ID:");

        jTextField_stid.setEditable(false);
        jTextField_stid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton_edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FName", "LName", "Gender", "BOD", "TP", "Add"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTextField_searchStu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_searchStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchStuActionPerformed(evt);
            }
        });
        jTextField_searchStu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_searchStuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchStuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_searchStuKeyTyped(evt);
            }
        });

        jLabel_slbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_slbl.setText("Enter the Option To serach :");

        jButton_studentCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_studentCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel1.png"))); // NOI18N
        jButton_studentCancel.setText("Cancel");
        jButton_studentCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_studentCancelActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stuGp.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/abc4_new.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_id))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton_fema))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jTextField_tp)
                            .addComponent(jDateChooserBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_LName)
                            .addComponent(jTextField_FName)
                            .addComponent(jTextField_stid))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton_manage_remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_mange_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton_edit)
                        .addGap(27, 27, 27)
                        .addComponent(jButton_mange_add, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_studentCancel))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_slbl)
                        .addGap(29, 29, 29)
                        .addComponent(jTextField_searchStu, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_searchStu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_slbl)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_stid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_id))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_FName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_LName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton_fema)
                                    .addComponent(jRadioButton_male)
                                    .addComponent(jLabel4))))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooserBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_tp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_manage_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_mange_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_mange_add, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_studentCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_tpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tpActionPerformed

    private void jTextField_tpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_tpKeyTyped
        // allow only numbers
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_tpKeyTyped

    private void jTextField_LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LNameActionPerformed

    private void jButton_mange_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mange_addActionPerformed

                AddStudentInfo as = new  AddStudentInfo();
                as.setVisible(true);
                as.pack();
                as.setLocationRelativeTo(null);
                as.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton_mange_addActionPerformed

    private void jButton_manage_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_manage_removeActionPerformed
        
        if(jTextField_stid.getText().equals("")){
         JOptionPane.showMessageDialog(null, "No student selected");
        
        }else{
        String id = jTextField_stid.getText();
        std.insertUpdateDeleteStudent('d', id, null, null, null, null, null, null);    
        std.fillStudentJtable(ManageStudentsInfo.jTable1, "");
        
        ManageStudentsInfo.jTable1.setModel(new DefaultTableModel(null,new Object[]{"StudentID","FirstName","LastName","Gender","Birthdate","PhoneNo","Address"}));
        std.fillStudentJtable(jTable1, jTextField_searchStu.getText());
       MainFrame.jLabel_StdCount.setText(" Total Students :"+Integer.toString(MyFunction.countData("student")));
       
        jTextField_stid.setText("");
        jTextArea_add.setText("");
        jTextField_FName.setText("");
        jTextField_LName.setText("");
        jTextField_tp.setText("");
        jRadioButton_fema.setSelected(false);
        jRadioButton_male.setSelected(false);
        jDateChooserBirth.setDate(null);
       
        }
    }//GEN-LAST:event_jButton_manage_removeActionPerformed

    public boolean veriText(){
        if(jTextField_FName.getText().equals("")||jTextField_LName.getText().equals("")||jTextField_tp.getText().equals("")||jTextArea_add.getText().equals("")||jTextField_stid.getText().equals("")||jDateChooserBirth.getDate()==null){
             JOptionPane.showMessageDialog(null, "One or more empty field");
            return false;
         
         //choose a date higher than the current date    
        }else if(jDateChooserBirth.getDate().compareTo(new Date())>0){
            JOptionPane.showMessageDialog(null, "No student from the Future are not allowed");
            return false;
        }
        else{
             return true;
        }
            
       
    }
    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        String fname=jTextField_FName.getText();
        String lname=jTextField_LName.getText();
        String phone=jTextField_tp.getText();
        String address=jTextArea_add.getText();
        String id =jTextField_stid.getText();
        String gender="";
        if(jRadioButton_fema.isSelected()){
            gender="Female";
        }
        else if(jRadioButton_male.isSelected()){
             gender="Male";
        }

        if(veriText()){

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String bdate = dateFormat.format(jDateChooserBirth.getDate());

            student std=new student();
            std.insertUpdateDeleteStudent('u', id, fname, lname, gender, bdate, phone, address);
            
            //change instanlt in table
            ManageStudentsInfo.jTable1.setModel(new DefaultTableModel(null,new Object[]{"StudentID","FirstName","LastName","Gender","Birthdate","PhoneNo","Address"}));
            std.fillStudentJtable(ManageStudentsInfo.jTable1, "");
              
        } 
                
    }//GEN-LAST:event_jButton_editActionPerformed
    int rowIndex;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       rowIndex = jTable1.getSelectedRow();
      
       if(model.getValueAt(rowIndex, 3).toString().equals("Male")){
           jRadioButton_male.setSelected(true);
           jRadioButton_fema.setSelected(false);
       }
       else{
            jRadioButton_fema.setSelected(true);
            jRadioButton_male.setSelected(false);
       }
       
       jTextField_stid.setText(model.getValueAt(rowIndex, 0).toString());
       jTextField_FName.setText(model.getValueAt(rowIndex, 1).toString());
       jTextField_LName.setText(model.getValueAt(rowIndex, 2).toString());      
       jTextField_tp.setText(model.getValueAt(rowIndex, 5).toString());
       jTextArea_add.setText(model.getValueAt(rowIndex, 6).toString());
       
       Date bdate;
      try{
          bdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
          jDateChooserBirth.setDate(bdate);
      } catch(ParseException ex){
          Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
          
      }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_searchStuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchStuKeyTyped
         
         
    }//GEN-LAST:event_jTextField_searchStuKeyTyped

    private void jTextField_searchStuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchStuKeyPressed
      
    }//GEN-LAST:event_jTextField_searchStuKeyPressed

    private void jTextField_searchStuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchStuKeyReleased
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"StudentID","FirstName","LastName","Gender","Birthdate","PhoneNo","Address"}));
        std.fillStudentJtable(jTable1, jTextField_searchStu.getText());
        
    }//GEN-LAST:event_jTextField_searchStuKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_UP||evt.getKeyCode()== KeyEvent.VK_DOWN)
        {
            rowIndex = jTable1.getSelectedRow();
           jTextField_stid.setText(model.getValueAt(rowIndex, 0).toString());
           jTextField_FName.setText(model.getValueAt(rowIndex, 1).toString());
           jTextField_LName.setText(model.getValueAt(rowIndex, 2).toString());      
           jTextField_tp.setText(model.getValueAt(rowIndex, 5).toString());
           jTextArea_add.setText(model.getValueAt(rowIndex, 6).toString());
         
         
          if(model.getValueAt(rowIndex, 3).toString().equals("Male")){
           jRadioButton_male.setSelected(true);
           jRadioButton_fema.setSelected(false);
       }
       else{
            jRadioButton_fema.setSelected(true);
            jRadioButton_male.setSelected(false);
       }
          
          
           Date bdate;
      try{
          bdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
          jDateChooserBirth.setDate(bdate);
         } catch(ParseException ex){
          Logger.getLogger(ManageStudentsInfo.class.getName()).log(Level.SEVERE, null, ex);
          
             }
     }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButton_mange_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mange_clearActionPerformed
        jTextField_stid.setText("");
        jTextArea_add.setText("");
        jTextField_FName.setText("");
        jTextField_LName.setText("");
        jTextField_tp.setText("");
        jRadioButton_fema.setSelected(false);
        jRadioButton_male.setSelected(false);
        jDateChooserBirth.setDate(null);
    }//GEN-LAST:event_jButton_mange_clearActionPerformed

    private void jButton_studentCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_studentCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_studentCancelActionPerformed

    private void jTextField_searchStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchStuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchStuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudentsInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_manage_remove;
    private javax.swing.JButton jButton_mange_add;
    private javax.swing.JButton jButton_mange_clear;
    private javax.swing.JButton jButton_studentCancel;
    private com.toedter.calendar.JDateChooser jDateChooserBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_slbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_fema;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_add;
    private javax.swing.JTextField jTextField_FName;
    private javax.swing.JTextField jTextField_LName;
    private javax.swing.JTextField jTextField_searchStu;
    private javax.swing.JTextField jTextField_stid;
    private javax.swing.JTextField jTextField_tp;
    // End of variables declaration//GEN-END:variables
}
