/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.system.student;

import static com.system.student.ManageStudentsInfo.jTable1;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ManageLecturerInfo extends javax.swing.JFrame {

    /**
     * Creates new form ManageLecturerInfo
     */
    Lecturer lec = new Lecturer();
    DefaultTableModel model;
    public ManageLecturerInfo() {
        initComponents();
        lec. fillLecturerJtable(jTable2,"");
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton_Lecturer_female);
        bg.add(jRadioButton_Lecturer_male);
        model =(DefaultTableModel)jTable2.getModel();
        jTable2.setRowHeight(30);
        jTable2.setShowGrid(true);
        jTable2.setGridColor(Color.black);
        jTable2.setSelectionBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Lecturer_tp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Lecturer_address = new javax.swing.JTextArea();
        jDateChooserBirth_Lecturer = new com.toedter.calendar.JDateChooser();
        jRadioButton_Lecturer_female = new javax.swing.JRadioButton();
        jRadioButton_Lecturer_male = new javax.swing.JRadioButton();
        jTextField_Lecturer_LName = new javax.swing.JTextField();
        jTextField_LecturerFName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_Lecturer_AddMa = new javax.swing.JButton();
        jButton_Lecturer_remove = new javax.swing.JButton();
        jButton_Lecturer_Edit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Lec_Search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Lecturer_ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TP_NO :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Birth of date :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Gender :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Last Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name :");

        jTextField_Lecturer_tp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Lecturer_tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Lecturer_tpActionPerformed(evt);
            }
        });
        jTextField_Lecturer_tp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Lecturer_tpKeyTyped(evt);
            }
        });

        jTextArea_Lecturer_address.setColumns(20);
        jTextArea_Lecturer_address.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea_Lecturer_address.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Lecturer_address);

        jDateChooserBirth_Lecturer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jRadioButton_Lecturer_female.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton_Lecturer_female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton_Lecturer_female.setText("Female");

        jRadioButton_Lecturer_male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton_Lecturer_male.setText("Male");

        jTextField_Lecturer_LName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Lecturer_LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Lecturer_LNameActionPerformed(evt);
            }
        });

        jTextField_LecturerFName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Curlz MT", 1, 36)); // NOI18N
        jLabel1.setText("Manage Lecturer Info");

        jButton_Lecturer_AddMa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Lecturer_AddMa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add1.png"))); // NOI18N
        jButton_Lecturer_AddMa.setText("Add");
        jButton_Lecturer_AddMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Lecturer_AddMaActionPerformed(evt);
            }
        });

        jButton_Lecturer_remove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Lecturer_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png"))); // NOI18N
        jButton_Lecturer_remove.setText("Remove");
        jButton_Lecturer_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Lecturer_removeActionPerformed(evt);
            }
        });

        jButton_Lecturer_Edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Lecturer_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        jButton_Lecturer_Edit.setText("Edit");
        jButton_Lecturer_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Lecturer_EditActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LecturerID", "FirstName", "LastName", "Gender", "Birthdatel", "PhoneNo", "Address"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Enter the Value to Serach :");

        jTextField_Lec_Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Lec_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Lec_SearchKeyReleased(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gpLec.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/abc4_new.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Lecturer ID :");

        jTextField_Lecturer_ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel11))
                                        .addGap(26, 26, 26))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_Lecturer_LName, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jRadioButton_Lecturer_male)
                                                .addGap(32, 32, 32)
                                                .addComponent(jRadioButton_Lecturer_female))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooserBirth_Lecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_Lecturer_tp, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField_Lecturer_ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jTextField_LecturerFName, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton_Lecturer_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton_Lecturer_Edit)
                                .addGap(31, 31, 31)
                                .addComponent(jButton_Lecturer_AddMa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(384, 384, 384)
                                .addComponent(jLabel8)
                                .addGap(26, 26, 26)
                                .addComponent(jTextField_Lec_Search))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Lec_Search))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_Lecturer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_LecturerFName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Lecturer_LName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jRadioButton_Lecturer_male)
                            .addComponent(jRadioButton_Lecturer_female))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooserBirth_Lecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_Lecturer_tp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Lecturer_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Lecturer_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Lecturer_AddMa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Lecturer_tpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Lecturer_tpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Lecturer_tpActionPerformed

    private void jTextField_Lecturer_tpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Lecturer_tpKeyTyped
        // allow only numbers
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_Lecturer_tpKeyTyped

    private void jTextField_Lecturer_LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Lecturer_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Lecturer_LNameActionPerformed

    private void jButton_Lecturer_AddMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Lecturer_AddMaActionPerformed

                AddLecturerInfo AddLec = new  AddLecturerInfo();
                AddLec.setVisible(true);
                AddLec.pack();
                AddLec.setLocationRelativeTo(null);
                AddLec.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton_Lecturer_AddMaActionPerformed

    private void jButton_Lecturer_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Lecturer_removeActionPerformed
       if(jTextField_Lecturer_ID.getText().equals("")){
         JOptionPane.showMessageDialog(null, "No lecturer selected");
        
        }else{
        int id = Integer.valueOf(jTextField_Lecturer_ID.getText());
        lec.insertUpdateDeleteStudent('d', id, null, null, null, null, null, null);    
        lec. fillLecturerJtable(ManageLecturerInfo.jTable2, "");
        
        ManageLecturerInfo.jTable2.setModel(new DefaultTableModel(null,new Object[]{"Id","First name","Last Name","Gender","Birthdate","Phone Number","Address",}));
        lec. fillLecturerJtable(jTable2, jTextField_Lec_Search.getText());
        //MainFrame.jLabel_StdCount.setText(" Total Students :"+Integer.toString(MyFunction.countData("student")));
       
        jTextField_Lecturer_ID.setText("");
        jTextArea_Lecturer_address.setText("");
        jTextField_LecturerFName.setText("");
        jTextField_Lecturer_LName.setText("");
        jTextField_Lecturer_tp.setText("");
        jRadioButton_Lecturer_female.setSelected(false);
        jRadioButton_Lecturer_male.setSelected(false);
        jDateChooserBirth_Lecturer.setDate(null);
       
        }
    }//GEN-LAST:event_jButton_Lecturer_removeActionPerformed

    
    
     public boolean veriText(){
        if(jTextField_LecturerFName.getText().equals("")||jTextField_Lecturer_LName.getText().equals("")||jTextField_Lecturer_tp.getText().equals("")||jTextArea_Lecturer_address.getText().equals("")||jTextField_Lecturer_ID.getText().equals("")||jDateChooserBirth_Lecturer.getDate()==null){
             JOptionPane.showMessageDialog(null, "One or more empty field");
            return false;
         
         //choose a date higher than the current date    
        }else if(jDateChooserBirth_Lecturer.getDate().compareTo(new Date())>0){
            JOptionPane.showMessageDialog(null, "No lecturer from the Future are not allowed");
            return false;
        }
        else{
             return true;
        }
            
       
    }
    private void jButton_Lecturer_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Lecturer_EditActionPerformed

        String fname=jTextField_LecturerFName.getText();
        String lname=jTextField_Lecturer_LName.getText();
        String phone=jTextField_Lecturer_tp.getText();
        String address=jTextArea_Lecturer_address.getText();
        int id =Integer.valueOf(jTextField_Lecturer_ID.getText());
        String gender="";
        if(jRadioButton_Lecturer_female.isSelected()){
            gender="Female";
        }
        else if(jRadioButton_Lecturer_male.isSelected()){
             gender="Male";
        }

        if(veriText()){

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String bdate = dateFormat.format(jDateChooserBirth_Lecturer.getDate());

            Lecturer lec = new Lecturer();
            lec.insertUpdateDeleteStudent('u', id, fname, lname, gender, bdate, phone, address);
            
            //change instanlt in table
            ManageLecturerInfo.jTable2.setModel(new DefaultTableModel(null,new Object[]{"Id","First name","Last Name","Gender","Birthdate","Phone Number","Address",}));
            lec.fillLecturerJtable(ManageLecturerInfo.jTable2, "");
              
        } 
                
    }//GEN-LAST:event_jButton_Lecturer_EditActionPerformed

    int rowIndex;
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        rowIndex = jTable2.getSelectedRow();
      
       if(model.getValueAt(rowIndex, 3).toString().equals("Male")){
           jRadioButton_Lecturer_male.setSelected(true);
           jRadioButton_Lecturer_female.setSelected(false);
       }
       else{
            jRadioButton_Lecturer_female.setSelected(true);
            jRadioButton_Lecturer_male.setSelected(false);
       }
       
        jTextField_Lecturer_ID.setText(model.getValueAt(rowIndex, 0).toString());
       jTextField_LecturerFName.setText(model.getValueAt(rowIndex, 1).toString());
       jTextField_Lecturer_LName.setText(model.getValueAt(rowIndex, 2).toString());      
       jTextField_Lecturer_tp.setText(model.getValueAt(rowIndex, 5).toString());
       jTextArea_Lecturer_address.setText(model.getValueAt(rowIndex, 6).toString());
       
       Date bdate;
      try{
          bdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
          jDateChooserBirth_Lecturer.setDate(bdate);
      } catch(ParseException ex){
          Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
          
      }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_UP||evt.getKeyCode()== KeyEvent.VK_DOWN)
        {
            rowIndex = jTable2.getSelectedRow();
            jTextField_Lecturer_ID.setText(model.getValueAt(rowIndex, 0).toString());
           jTextField_LecturerFName.setText(model.getValueAt(rowIndex, 1).toString());
           jTextField_Lecturer_LName.setText(model.getValueAt(rowIndex, 2).toString());      
            jTextField_Lecturer_tp.setText(model.getValueAt(rowIndex, 5).toString());
          jTextArea_Lecturer_address.setText(model.getValueAt(rowIndex, 6).toString());
         
         
          if(model.getValueAt(rowIndex, 3).toString().equals("Male")){
            jRadioButton_Lecturer_male.setSelected(true);
           jRadioButton_Lecturer_female.setSelected(false);
       }
       else{
            jRadioButton_Lecturer_female.setSelected(true);
             jRadioButton_Lecturer_male.setSelected(false);
       }
          
          
           Date bdate;
      try{
          bdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
          jDateChooserBirth_Lecturer.setDate(bdate);
         } catch(ParseException ex){
          Logger.getLogger(ManageStudentsInfo.class.getName()).log(Level.SEVERE, null, ex);
          
             }
     }
    }//GEN-LAST:event_jTable2KeyReleased

    private void jTextField_Lec_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Lec_SearchKeyReleased
        jTable2.setModel(new DefaultTableModel(null,new Object[]{"Id","First name","Last Name","Gender","Birthdate","Phone Number","Address",}));
        lec.fillLecturerJtable(jTable2, jTextField_Lec_Search.getText());
    }//GEN-LAST:event_jTextField_Lec_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageLecturerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageLecturerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageLecturerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageLecturerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageLecturerInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Lecturer_AddMa;
    private javax.swing.JButton jButton_Lecturer_Edit;
    private javax.swing.JButton jButton_Lecturer_remove;
    private com.toedter.calendar.JDateChooser jDateChooserBirth_Lecturer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton_Lecturer_female;
    private javax.swing.JRadioButton jRadioButton_Lecturer_male;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea_Lecturer_address;
    private javax.swing.JTextField jTextField_Lec_Search;
    private javax.swing.JTextField jTextField_LecturerFName;
    private javax.swing.JTextField jTextField_Lecturer_ID;
    private javax.swing.JTextField jTextField_Lecturer_LName;
    private javax.swing.JTextField jTextField_Lecturer_tp;
    // End of variables declaration//GEN-END:variables
}
